services:
  backend:
    image: msmkd/kittygram_backend
    container_name: backend
    restart: always
    env_file: .env
    networks:
      - kittygram-network
    volumes:
      - static:/backend_static
      - media:/media_static
    depends_on:
      - postgres

  frontend:
    image: msmkd/kittygram_frontend
    container_name: frontend
    restart: always
    networks:
      - kittygram-network
    volumes:
      - frontend:/app/build

  gateway:
    image: msmkd/kittygram_gateway
    container_name: gateway
    ports:
      - '80:80'
      - '8000:80'    
    restart: always
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram-network
    volumes:
      - static:/static
      - media:/media_static
      - frontend:/frontend

  postgres:
    image: postgres:13
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data  # Данные PostgreSQL
    networks:
      - kittygram-network

volumes:
  pg_data:    # Для базы данных
  static:     # Для статики
  media:      # Для медиафайлов
  frontend:   # Для фронтенда

networks:
  kittygram-network:
    driver: bridge
