volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  postgres:
    image: postgres:13.10
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: msmkd/kittygram_backend:latest
    env_file: .env
    restart: always
    depends_on:
      - kitty_postgres
    volumes:
      - static:/app/collected_static/
      - media:/app/media/    

  frontend:
    image: msmkd/kittygram_frontend:latest
    env_file: .env
    restart: always
    volumes:
      - frontend_build:/app/build/
  
  gateway:
    image: msmkd/kittygram_gateway:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - frontend_build:/usr/share/nginx/html/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - kitty_backend
      - kitty_frontend